export const GET_ROLE_USER = "GET_ROLE_USER";
export const FETCH_REQUESTS = "FETCH_REQUESTS";
export const NEW_REQUEST = "NEW_REQUEST";
export const PENDING_REQUESTS = "PENDING_REQUESTS";
export const FETCH_BUSINESS_AREAS = "FETCH_BUSINESS_AREAS";
